# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8fc8e763632366a17f79d130c8a6bbc6ab88351f102e6f66fe2980886296c4a12a596bba51969c962c788ecf44ad7e81a3003be1f900c3afccdf09d30d7f24d

test:
  secret_key_base: 4a7e25ca0ab283cac9db421fa18a1b58db7fabef465db9e748f008ad5c62012d48d06347f13f968ade1f09b300e32e0b547818f97b189d398331cc39b013735b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
